export interface Data {
    about: string;
    birthday: string;
    birthdaychild1: string;
    birthdaychild2: string;
    birthdaychild3: string;
    birthdaychild4: string;
    birthyear: string;
    children: string;
    city: string;
    color: null | string;
    comment: string;
    comp: string;
    dateofend: string | Date;
    defer: string | number;
    email: string;
    familystatus: string;
    fav: string;
    fav_date: string;
    fav_modify: string;
    fb: string;
    firstname: string;
    gender: string;
    height: string;
    helptext: string;
    id: string ;
    images: string;
    inst: string;
    langlove: string;
    langlove2: string;
    last_modify: string;
    lastlove: string;
    lastzodiak: string;
    next_contact_date: null | string;
    ok: string;
    password: string;
    visible_pass: string | null;
    phone: string;
    reg_date: string;
    registermonth: string;
    report: string;
    role: string | number;
    smoke: string;
    source: string;
    source_type: string;
    status: string | number;
    targetsearch: string;
    targetsearchtext: string;
    uid: string | number;
    user_InNum: string | number;
    user_OutNum: string | number;
    vip: string | number;
    vk: string;
    weight: string | number;
    year: string | number;
    zodiak: string;
    dragableColor: string | null
}
